# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    env(CARDTRADER_API_TOKEN): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $cardTraderApiToken: '%env(CARDTRADER_API_TOKEN)%'

    App\:
        resource: '../src/'
